<a href="https://colab.research.google.com/github/kazimovmirkazim/Machine-Learning/blob/main/ML_Obesity_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!/bin/bash
!curl -L -o obesity-prediction-dataset.zip https://www.kaggle.com/api/v1/datasets/download/adeniranstephen/obesity-prediction-dataset

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33445  100 33445    0     0  62120      0 --:--:-- --:--:-- --:--:-- 1128k


In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [ ]:
!unzip /content/obesity-prediction-dataset.zip

Archive:  /content/obesity-prediction-dataset.zip
  inflating: ObesityDataSet_raw_and_data_sinthetic.csv  


In [ ]:
df = pd.read_csv('/content/ObesityDataSet_raw_and_data_sinthetic.csv')
df

Gender  Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0     Female   21    1.62   64.00                            yes   no   2.0   
1     Female   21    1.52   56.00                            yes   no   3.0   
2       Male   23    1.80   77.00                            yes   no   2.0   
3       Male   27    1.80   87.00                             no   no   3.0   
4       Male   22    1.78   89.80                             no   no   2.0   
...      ...  ...     ...     ...                            ...  ...   ...   
2106  Female   21    1.71  131.41                            yes  yes   3.0   
2107  Female   22    1.75  133.74                            yes  yes   3.0   
2108  Female   23    1.75  133.69                            yes  yes   3.0   
2109  Female   24    1.74  133.35                            yes  yes   3.0   
2110  Female   24    1.74  133.47                            yes  yes   3.0   

      NCP       CAEC SMOKE  CH2O  SCC   FAF    TUE        CALC  \
0     3.0  Sometimes    no  2.00   no  0.00  1.000          no   
1     3.0  Sometimes   yes  3.00  yes  3.00  0.000   Sometimes   
2     3.0  Sometimes    no  2.00   no  2.00  1.000  Frequently   
3     3.0  Sometimes    no  2.00   no  2.00  0.000  Frequently   
4     1.0  Sometimes    no  2.00   no  0.00  0.000   Sometimes   
...   ...        ...   ...   ...  ...   ...    ...         ...   
2106  3.0  Sometimes    no  1.73   no  1.68  0.906   Sometimes   
2107  3.0  Sometimes    no  2.01   no  1.34  0.599   Sometimes   
2108  3.0  Sometimes    no  2.05   no  1.41  0.646   Sometimes   
2109  3.0  Sometimes    no  2.85   no  1.14  0.586   Sometimes   
2110  3.0  Sometimes    no  2.86   no  1.03  0.714   Sometimes   

                     MTRANS           NObeyesdad  
0     Public_Transportation        Normal_Weight  
1     Public_Transportation        Normal_Weight  
2     Public_Transportation        Normal_Weight  
3                   Walking   Overweight_Level_I  
4     Public_Transportation  Overweight_Level_II  
...                     ...                  ...  
2106  Public_Transportation     Obesity_Type_III  
2107  Public_Transportation     Obesity_Type_III  
2108  Public_Transportation     Obesity_Type_III  
2109  Public_Transportation     Obesity_Type_III  
2110  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [ ]:
df.isna().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [ ]:
X= df.drop('NObeyesdad',axis=1)
y=  df['NObeyesdad'].copy()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.model_selection import train_test_split
X_train_full,X_test,y_train_full,y_test = train_test_split(X,y,test_size=0.2,random_state=13)
X_train,X_val,y_train,y_val = train_test_split(X_train_full,y_train_full,test_size=0.2)

In [ ]:
encoder= LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_train

array([2, 5, 6, ..., 5, 1, 2])

In [ ]:
y_val = encoder.fit_transform(y_val)
y_val

array([1, 0, 6, 6, 5, 0, 5, 4, 2, 0, 2, 6, 2, 0, 2, 0, 2, 3, 4, 1, 3, 3,
       0, 4, 5, 0, 5, 6, 6, 1, 6, 3, 5, 6, 5, 3, 2, 2, 4, 5, 4, 5, 6, 4,
       5, 0, 4, 6, 2, 1, 1, 5, 2, 2, 4, 5, 5, 6, 5, 0, 0, 2, 2, 6, 1, 6,
       4, 5, 1, 5, 0, 4, 5, 4, 4, 5, 4, 2, 4, 2, 1, 4, 4, 0, 1, 4, 6, 0,
       1, 2, 2, 3, 2, 6, 6, 5, 4, 1, 2, 4, 4, 2, 3, 0, 5, 4, 6, 2, 2, 4,
       2, 4, 3, 6, 5, 1, 4, 5, 2, 6, 5, 2, 5, 0, 5, 0, 4, 3, 4, 2, 3, 6,
       1, 5, 1, 6, 0, 0, 2, 0, 2, 3, 5, 1, 5, 4, 2, 4, 4, 3, 4, 4, 2, 2,
       1, 5, 1, 5, 0, 2, 0, 4, 5, 1, 4, 1, 5, 6, 4, 6, 4, 2, 5, 1, 1, 5,
       6, 4, 1, 6, 4, 3, 3, 1, 0, 5, 3, 4, 0, 1, 0, 2, 5, 4, 4, 4, 5, 4,
       1, 6, 3, 4, 6, 6, 1, 4, 1, 1, 1, 0, 3, 2, 2, 1, 0, 5, 5, 4, 6, 5,
       3, 0, 3, 5, 0, 4, 6, 1, 0, 1, 1, 1, 6, 0, 4, 4, 2, 0, 4, 6, 1, 5,
       2, 1, 6, 0, 1, 2, 3, 0, 4, 0, 3, 3, 2, 1, 2, 5, 6, 5, 6, 1, 1, 1,
       0, 1, 1, 3, 2, 3, 4, 2, 0, 6, 1, 2, 0, 5, 5, 6, 1, 5, 5, 0, 4, 5,
       3, 3, 5, 4, 4, 6, 2, 6, 5, 6, 5, 0, 6, 5, 3,

In [ ]:
y_test = encoder.transform(y_test)
y_test

array([6, 2, 2, 4, 3, 5, 3, 4, 5, 4, 2, 6, 3, 6, 0, 4, 1, 4, 2, 1, 2, 1,
       1, 5, 3, 0, 6, 1, 4, 4, 3, 5, 5, 1, 0, 4, 6, 2, 3, 2, 6, 3, 2, 3,
       4, 2, 6, 5, 0, 2, 4, 4, 0, 2, 5, 1, 1, 6, 4, 2, 5, 6, 4, 3, 5, 6,
       4, 2, 1, 1, 1, 2, 5, 1, 0, 2, 4, 0, 4, 0, 2, 6, 4, 2, 6, 5, 5, 2,
       3, 3, 5, 4, 5, 2, 3, 5, 2, 3, 4, 3, 4, 6, 1, 4, 6, 2, 0, 4, 5, 4,
       6, 6, 0, 6, 2, 3, 5, 5, 2, 5, 5, 0, 3, 5, 2, 6, 0, 2, 0, 6, 0, 3,
       2, 2, 2, 3, 5, 1, 6, 6, 3, 5, 4, 2, 2, 4, 3, 5, 5, 4, 4, 5, 0, 4,
       3, 1, 1, 1, 1, 0, 3, 5, 4, 3, 1, 6, 0, 6, 4, 5, 5, 6, 1, 3, 6, 5,
       5, 2, 3, 5, 0, 3, 1, 0, 0, 4, 2, 5, 6, 5, 1, 2, 6, 2, 4, 1, 4, 1,
       1, 4, 1, 0, 3, 5, 0, 5, 5, 0, 0, 1, 5, 5, 2, 6, 1, 2, 3, 1, 0, 5,
       5, 0, 0, 0, 1, 4, 2, 0, 6, 0, 1, 0, 2, 2, 3, 4, 3, 1, 0, 3, 5, 0,
       2, 3, 3, 4, 1, 1, 2, 3, 3, 5, 2, 1, 2, 5, 6, 4, 1, 6, 3, 2, 2, 2,
       4, 0, 0, 0, 6, 4, 4, 0, 4, 5, 3, 1, 1, 5, 6, 0, 6, 6, 3, 4, 2, 3,
       5, 4, 0, 6, 1, 5, 3, 6, 5, 3, 3, 0, 6, 3, 5,

In [ ]:
num_feature= X_train_full.select_dtypes(include=np.number).columns
cat_feature= X_train_full.select_dtypes(exclude=np.number).columns

In [ ]:
num_feature

Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], dtype='object')

In [ ]:
cat_feature

Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS'],
      dtype='object')

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

In [ ]:
num_pipeline= Pipeline(
    [
        ('imputer',SimpleImputer(strategy='median')),
        ('encoder',StandardScaler())
    ])
cat_pipeline = Pipeline([
    ('impute',SimpleImputer(strategy='constant',fill_value='missing')),
    ('encode',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

transformer = ColumnTransformer(
    [
        ('num',num_pipeline,num_feature),
        ('cat',cat_pipeline,cat_feature)
    ],remainder='passthrough'
)
estimator= RandomForestClassifier()
full_pipeline= Pipeline(
    [
        ('preprocessing',transformer),
        ('estimator',estimator)
    ]
)

In [ ]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('encoder',
                                                  StandardScaler())]),
                                 Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('encode',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS'],
      dtype='object'))])

In [ ]:
X_train_prepared = pd.DataFrame(transformer.fit_transform(X_train),columns=transformer.get_feature_names_out())
X_val_prepared = pd.DataFrame(transformer.transform(X_val),columns=transformer.get_feature_names_out())
X_test_prepared = pd.DataFrame(transformer.transform(X_val),columns=transformer.get_feature_names_out())


In [ ]:
X_train_prepared

num__Age  num__Height  num__Weight  num__FCVC  num__NCP  num__CH2O  \
0     2.088757    -0.894715    -0.265009   1.042223  0.407343  -0.615145   
1     1.934356    -1.855542    -0.934838  -0.232234  0.213925   1.020975   
2     1.471154    -0.254164    -0.379314   1.098449 -2.171565  -0.026142   
3    -0.690458    -0.254164     1.465574   1.098449  0.407343  -1.465927   
4    -0.227255     0.813421     1.019402  -1.225561  0.407343  -0.026142   
...        ...          ...          ...        ...       ...        ...   
1345 -0.536057     0.386387     1.675515   1.098449  0.407343  -0.271560   
1346  2.551960    -1.748783    -0.377409  -0.775753  0.407343   0.121109   
1347 -0.536057    -1.001474    -0.718039  -0.813237  1.116543   0.333805   
1348 -0.690458     0.172870    -0.646027   1.098449  0.407343  -1.662262   
1349  3.015162    -1.108232    -0.265009  -0.775753  0.407343   1.609978   

      num__FAF  num__TUE  cat__Gender_Female  cat__Gender_Male  ...  \
0    -1.176079 -1.050301                 1.0               0.0  ...   
1    -1.176079  0.584634                 1.0               0.0  ...   
2     0.001160 -1.050301                 1.0               0.0  ...   
3    -0.140109 -0.139621                 1.0               0.0  ...   
4     0.107111 -0.931516                 0.0               1.0  ...   
...        ...       ...                 ...               ...  ...   
1345  0.542689  0.536791                 1.0               0.0  ...   
1346 -1.176079 -1.050301                 1.0               0.0  ...   
1347 -0.022385 -0.291401                 1.0               0.0  ...   
1348 -1.176079 -1.050301                 0.0               1.0  ...   
1349 -1.176079 -1.050301                 0.0               1.0  ...   

      cat__SCC_no  cat__SCC_yes  cat__CALC_Frequently  cat__CALC_Sometimes  \
0             1.0           0.0                   0.0                  1.0   
1             1.0           0.0                   0.0                  1.0   
2             1.0           0.0                   0.0                  1.0   
3             1.0           0.0                   0.0                  1.0   
4             1.0           0.0                   0.0                  1.0   
...           ...           ...                   ...                  ...   
1345          1.0           0.0                   0.0                  1.0   
1346          1.0           0.0                   0.0                  1.0   
1347          1.0           0.0                   0.0                  1.0   
1348          1.0           0.0                   0.0                  1.0   
1349          1.0           0.0                   0.0                  0.0   

      cat__CALC_no  cat__MTRANS_Automobile  cat__MTRANS_Bike  \
0              0.0                     1.0               0.0   
1              0.0                     1.0               0.0   
2              0.0                     1.0               0.0   
3              0.0                     0.0               0.0   
4              0.0                     0.0               0.0   
...            ...                     ...               ...   
1345           0.0                     0.0               0.0   
1346           0.0                     1.0               0.0   
1347           0.0                     0.0               0.0   
1348           0.0                     0.0               0.0   
1349           1.0                     0.0               0.0   

      cat__MTRANS_Motorbike  cat__MTRANS_Public_Transportation  \
0                       0.0                                0.0   
1                       0.0                                0.0   
2                       0.0                                0.0   
3                       0.0                                1.0   
4                       0.0                                1.0   
...                     ...                                ...   
1345                    0.0                                1.0   
1346  

In [ ]:
import tensorflow  as tf
model= tf.keras.Sequential([
     tf.keras.layers.Input(shape=[30]),
tf.keras.layers.Flatten(),
tf.keras.layers.BatchNormalization(),
tf.keras.layers.Dense(100,activation='relu',kernel_initializer='he_normal'),
tf.keras.layers.BatchNormalization(),
tf.keras.layers.Dense(80,activation='relu',kernel_initializer='he_normal'),
tf.keras.layers.BatchNormalization(),
tf.keras.layers.Dense(50,activation='relu',kernel_initializer='he_normal'),
tf.keras.layers.BatchNormalization(),
tf.keras.layers.Dense(7,activation='softmax')
]
)
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              metrics=['accuracy'])


In [ ]:
model.fit(X_train_prepared,y_train,epochs=5,validation_data=(X_val_prepared,y_val))

Epoch 1/5
43/43 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.3275 - loss: 1.9734 - val_accuracy: 0.4675 - val_loss: 1.5080
Epoch 2/5
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6817 - loss: 0.9554 - val_accuracy: 0.6391 - val_loss: 1.1708
Epoch 3/5
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7318 - loss: 0.7854 - val_accuracy: 0.6834 - val_loss: 0.9468
Epoch 4/5
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7738 - loss: 0.6878 - val_accuracy: 0.7160 - val_loss: 0.7998
Epoch 5/5
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8037 - loss: 0.5887 - val_accuracy: 0.7692 - val_loss: 0.7095
